[package]
name = "epoll-broadcaster"
version = "0.1.0"
edition = "2024"
default-run = "epoll-broadcaster"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"

[[bin]]
name = "client"
path = "src/bin/client.rs"